### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by oldesec** [deibit/cansina#35]
Hello,

I get the following error.

ctrl +c enter : error.

```
Keep a resume file? [y/N] y
setting line to 697
Traceback (most recent call last):
  File "cansina.py", line 411, in <module>
    visitors_alive = any([visitor.is_alive() for visitor in thread_pool])
  File "cansina.py", line 411, in <listcomp>
    visitors_alive = any([visitor.is_alive() for visitor in thread_pool])
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cansina.py", line 421, in <module>
    pickle.dump(resumer, f)
TypeError: write() argument must be str, not bytes
```

**Comment by deibit** [comment]
Hi, https://github.com/deibit/cansina/issues/28 'resumer' need a rework. It is on the agenda.
