### ISSUE TITLE
some running errors

### ISSUE THREAD

**Issue by theLSA** [deibit/cansina#42]
Hi,nice tool!
But I encountered two problems when using it.

1-
env: linux/win7+py2.7+cansinaPY27
python cansina.py -u https://www.xxx.com/ -p admin.txt -t 10 -H --full-path

output:
Requests:                      HEAD
Banned response codes:         404
Using payload:                 admin.txt
Threads:                       10
Total requests:                133 (aprox: 13 / thread)

cod |    size    |  line  | time |

Traceback (most recent call last):
  File "cansina.py", line 406, in <module>
    Console.set_show_colors(False if args.no_colors else True)
TypeError: unbound method set_show_colors() must be called with Console instance as first argument (got bool instance instead)

2-
env: win7+py3+cansina

c:\Python38\python cansina.py  -u https://www.xxx.com/ -p "D:\php\top3000.txt" -t 10 -H --full-path

output:
install asciitree for viewer feature
Traceback (most recent call last):
  File "cansina.py", line 483, in <module>
    Console.init()
  File "D:\cansina-master\core\printer.py", line 125, in init
    Console.clear()
  File "D:\cansina-master\core\printer.py", line 98, in clear
    sys.stdout.write(CLEARSCR)
NameError: name 'CLEARSCR' is not defined

Then I try add --no-colors and --no-progress:

c:\Python38\python cansina.py --no-colors --no-progress -u https://www.xxx.com/ -p "D:\php\top3000.txt" -t 10 -H --full-path

output:
install asciitree for viewer feature
[!] General exception while visiting
name 'DEL' is not defined

(By the way:when I try py3+cansina+llinux,output confusion.)

May I ask why?

**Comment by deibit** [comment]
Hi!

Thanks for giving it a try. 

case Win + Python 2.7:
&nbsp; &nbsp; Cansina is not supported in Python 2.7 at all. There is a [tag](https://github.com/deibit/cansina/tree/Py27) but I cannot assure it works.

case Win + Python 3:
&nbsp; &nbsp; Sorry, I do not have a Windows dev system nearby so I cannot test it. Definitely I should, but cannot say when I will do it.

case Linux + Python 3:
&nbsp; &nbsp; I see the bug there. It should be gone by installing "asciitree" but on the other hand it should be kept as an optional dependency. I will file a bug on this.

Again, thanks for using it.

**Comment by theLSA** [comment]
Hello, add some details.

env: linux+py3.9+cansina-master+asciitree0.3.3

python3 cansina.py -u https://www.xxx.com/ -p testdir.txt -t 10 -H --full-path

confused output:
![cansina-error-2021-06-09_22-52](https://user-images.githubusercontent.com/28248956/121396738-3eb85300-c986-11eb-963a-425053852eb2.png)

python3 cansina.py -V ./output/https_www.xxx.com.sqlite

the results are incomplete,without directory(http code 200)
![cansina-error-2021-06-09_22-52-1](https://user-images.githubusercontent.com/28248956/121396809-50015f80-c986-11eb-9425-f06376bb415b.png)

![cansina-error-2021-06-09_22-54](https://user-images.githubusercontent.com/28248956/121396834-54c61380-c986-11eb-957f-a0c094951c27.png)

**Comment by deibit** [comment]
Yes, "viewer" is not working as it should I will mark it for review. May I ask you what was your terminal columns number?  Please, take into account that resizing the terminal while cansina is running will introduce visible bugs as layout is not dynamic yet.

**Comment by theLSA** [comment]
80columns 24rows, all is default.

**Comment by deibit** [comment]
With those measures I can confirm your same results

![Screenshot 2021-06-10 at 14 55 35](https://user-images.githubusercontent.com/367532/121528982-4286bc80-c9fc-11eb-8464-997b1036b8c8.png)

Rows must be great enough to make room to all the information is being displayed. Also, columns >80 will help.

**Comment by theLSA** [comment]
Thanks! As you say, I make terminal max,it work better,but still have some bugs:
The progress bar always imcomplete even the dictionary was completed.
And I should use ctrl+c to end the program.
![cansina-error-2021-06-10_22-21](https://user-images.githubusercontent.com/28248956/121542778-fdce4600-ca3a-11eb-9284-ada3c270fd49.png)

**Comment by deibit** [comment]
This should happen only when there are pending threads waiting for a response. A timeout should kill them properly.
